export const quakeConstants = {
  CREATE_QUAKE_REQUEST: "CREATE_QUAKE_REQUEST",
  CREATE_QUAKE_SUCCESS: "CREATE_QUAKE_SUCCESS",
  CREATE_QUAKE_FAILURE: "CREATE_QUAKE_FAILURE",

  QUAKE_UPDATE_REQUEST: "QUAKE_UPDATE_REQUEST",
  QUAKE_UPDATE_SUCCESS: "QUAKE_UPDATE_SUCCESS",
  QUAKE_UPDATE_FAILURE: "QUAKE_UPDATE_FAILURE",

  GET_ALL_QUAKES_REQUEST: "GET_ALL_QUAKES_REQUEST",
  GET_ALL_QUAKES_SUCCESS: "GET_ALL_QUAKES_SUCCESS",
  GET_ALL_QUAKES_FAILURE: "GET_ALL_QUAKES_FAILURE",

  GET_QUAKE_REQUEST: "GET_QUAKE_REQUEST",
  GET_QUAKE_SUCCESS: "GET_QUAKE_SUCCESS",
  GET_QUAKE_FAILURE: "GET_QUAKE_FAILURE",

  DELETE_QUAKE_REQUEST: "DELETE_QUAKE_REQUEST",
  DELETE_QUAKE_SUCCESS: "DELETE_QUAKE_SUCCESS",
  DELETE_QUAKE_FAILURE: "DELETE_QUAKE_FAILURE"
};
