export const quakeConstants = {
  ADD_REQUEST: "QUAKES_ADD_REQUEST",
  ADD_SUCCESS: "QUAKES_ADD_SUCCESS",
  ADD_FAILURE: "QUAKES_ADD_FAILURE",

  UPDATE_REQUEST: "QUAKES_UPDATE_REQUEST",
  UPDATE_SUCCESS: "QUAKES_UPDATE_SUCCESS",
  UPDATE_FAILURE: "QUAKES_UPDATE_FAILURE",

  GETALL_REQUEST: "QUAKES_GETALL_REQUEST",
  GETALL_SUCCESS: "QUAKES_GETALL_SUCCESS",
  GETALL_FAILURE: "QUAKES_GETALL_FAILURE",

  GET_REQUEST: "QUAKES_GET_REQUEST",
  GET_SUCCESS: "QUAKES_GET_SUCCESS",
  GET_FAILURE: "QUAKES_GET_FAILURE",

  DELETE_REQUEST: "QUAKES_DELETE_REQUEST",
  DELETE_SUCCESS: "QUAKES_DELETE_SUCCESS",
  DELETE_FAILURE: "QUAKES_DELETE_FAILURE"
};
